name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VPS
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ deployuser@51.38.71.228:/home/deployuser/app

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@51.38.71.228 "cd /home/deployuser/app && docker-compose pull && docker-compose up -d --build"
