name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Write the SSH private key to the id_rsa file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        
        # Set permissions for the private key file
        chmod 600 ~/.ssh/id_rsa
        
        # Start the SSH agent
        eval "$(ssh-agent -s)"
        
        # Create the SSH_ASKPASS script
        echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass
        chmod +x ~/.ssh_askpass
        
        # Add the SSH key to the agent
        DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add ~/.ssh/id_rsa

    - name: Print SSH keys
      run: ssh-add -l

    - name: Copy files to VPS
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ deployuser@51.38.71.228:/home/deployuser/app

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@51.38.71.228 "cd /home/deployuser/app && docker-compose pull && docker-compose up -d --build"
