name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Setup the SSH agent
        mkdir -p ~/.ssh
        ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

    - name: Print SSH keys
      run: ssh-add -l

    - name: Copy files to VPS
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ deployuser@51.38.71.228:/home/deployuser/app

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@51.38.71.228 "cd /home/deployuser/app && docker-compose pull && docker-compose up -d --build"
